### ISSUE TITLE
registration.php needs to be added 

### ISSUE THREAD

**Issue by florinserbu2** [astorm/magento2-tutorial-objectmanager1#2]
Hi Alan,

I am following your tutorial on Object Manger and noticed that the registration.php file is missing from the tag 0.0.3 (linked in the article).

Just wanna let you know. 

Thanks!

**Comment by astorm** [comment]
@florinserbu2 Yeah -- I wrote these modules before registration.php was a thing.  Happy to accept pull requests -- otherwise I'll get to at some point in the far flung future.

**Comment by florinserbu2** [comment]
It's already added in the master branch but not on the 0.0.3 release which is linked in the tutorial. 

I would be happy to contribute and make a pull request but for some reason github is not allowing me to do that.

**Comment by astorm** [comment]
Ahhhhhh, double got it.  That's going to mean tagging up a new release 
and editing the article.  I'll add that my queue of Things to Get Done.

Thank you for taking the time to explaining the obvious to me in more 
detail ;).
- Alan
